services:
  rabbitmq:
    image: rabbitmq:alpine
    hostname: rabbitmq
    container_name: bigdata-book-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.1.7
    extra_hosts:
      - "metastore:172.28.1.1"
      - "master:172.28.1.2"
      - "worker1:172.28.1.3"
      - "worker2:172.28.1.4"
      - "history:172.28.1.5"
  metastore:
    image: postgres:11
    hostname: metastore
    container_name: bigdata-book-metastore
    environment:
      POSTGRES_PASSWORD: jupyter
    ports:
      - "5432:5432"
    volumes:
      - metastore:/var/lib/postgresql/data
      - ./ddl/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.1.1
    extra_hosts:
      - "master:172.28.1.2"
      - "worker1:172.28.1.3"
      - "worker2:172.28.1.4"
      - "history:172.28.1.5"
      - "rabbitmq:172.28.1.7"
  master:
    image: bigdata-book-master
    hostname: master
    privileged: true
    container_name: bigdata-book-master
    depends_on:
      - metastore
      - rabbitmq
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 172.28.1.2
      SPARK_LOCAL_HOSTNAME: master
      PYSPARK_PYTHON: python3.10
      PYSPARK_DRIVER_PYTHON: python3.10
      AIRFLOW_UI_ADMIN_USERNAME: admin
      AIRFLOW_UI_ADMIN_PASSWORD: admin
    ports:
      - "4040:4040"
      - "7077:7077"
      - "8020:8020"
      - "8080:8080" # Spark Master
      - "8089:8089" # Storm UI
      - "8088:8088" # Hadoop Resource Manager
      - "9870:9870" # Hadoop NameNode
      - "8096:8096" # Zookeeper Server
      - "10000:10000" # Hive URI
      - "8881:8881" # Airflow UI
    volumes:
      - namenode:/opt/hadoop/dfs/name
      - ./examples:/opt/examples
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.1.2
    extra_hosts:
      - "metastore:172.28.1.1"
      - "worker1:172.28.1.3"
      - "worker2:172.28.1.4"
      - "history:172.28.1.5"
      - "rabbitmq:172.28.1.7"
  worker1:
    image: bigdata-book-worker
    hostname: worker1
    container_name: bigdata-book-worker1
    depends_on:
      - master
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 172.28.1.3
      SPARK_LOCAL_HOSTNAME: worker1
      PYSPARK_PYTHON: python3.10
      PYSPARK_DRIVER_PYTHON: python3.10
    ports:
      - "8042:8042" # Hadoop Node Manager 1
      - "8081:8081" # Spark Worker 1
      - "8001:8000" # Storm Worker Log
      - "9864:9864" # Hadoop Datanode 1
    volumes:
      - datanode1:/opt/hadoop/dfs/data
      - ./examples:/opt/examples
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.1.3
    extra_hosts:
      - "metastore:172.28.1.1"
      - "master:172.28.1.2"
      - "worker2:172.28.1.4"
      - "history:172.28.1.5"
      - "rabbitmq:172.28.1.7"
  worker2:
    image: bigdata-book-worker
    container_name: bigdata-book-worker2
    hostname: worker2
    depends_on:
      - master
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 172.28.1.4
      SPARK_LOCAL_HOSTNAME: worker2
      PYSPARK_PYTHON: python3.10
      PYSPARK_DRIVER_PYTHON: python3.10
    ports:
      - "8043:8042" # Hadoop Node Manager 2
      - "8002:8000" # Storm Worker Log
      - "8082:8081" # Spark Worker 2
      - "9865:9864" # Hadoop Datanode 2
    volumes:
      - datanode2:/opt/hadoop/dfs/data
      - ./examples:/opt/examples
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.1.4
    extra_hosts:
      - "metastore:172.28.1.1"
      - "master:172.28.1.2"
      - "worker1:172.28.1.3"
      - "history:172.28.1.5"
      - "rabbitmq:172.28.1.7"
  history:
    image: bigdata-book-history
    hostname: history
    container_name: bigdata-book-history
    depends_on:
      - master
      - worker1
      - worker2
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 172.28.1.5
      SPARK_LOCAL_HOSTNAME: history
      PYSPARK_PYTHON: python3.10
      PYSPARK_DRIVER_PYTHON: python3.10
    ports:
      - "18080:18080"
      - "19888:19888" # Hadoop History Server
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.1.5
    extra_hosts:
      - "metastore:172.28.1.1"
      - "master:172.28.1.2"
      - "worker1:172.28.1.3"
      - "worker2:172.28.1.4"
      - "rabbitmq:172.28.1.7"
  jupyter:
    image: bigdata-book-jupyter
    hostname: jupyter
    container_name: bigdata-book-jupyter
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 172.28.1.6
      SPARK_LOCAL_HOSTNAME: jupyter
      PYSPARK_PYTHON: python3.10
      PYSPARK_DRIVER_PYTHON: python3.10
    depends_on:
      - master
      - worker1
      - worker2
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter/notebook:/notebook
      - ./jupyter/run.sh:/usr/local/sbin/run.sh
      - ./examples:/opt/examples
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.1.6
    extra_hosts:
      - "metastore:172.28.1.1"
      - "master:172.28.1.2"
      - "worker1:172.28.1.3"
      - "worker2:172.28.1.4"
      - "history:172.28.1.5"
      - "rabbitmq:172.28.1.7"
volumes:
  namenode:
  datanode1:
  datanode2:
  metastore:

networks:
  sparknet:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16